# Generated by Django 3.2.13 on 2022-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20220524_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='42-50', max_length=255),
        ),
    ]
