# Generated by Django 3.2.13 on 2022-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_publicoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10)),
            ],
        ),
    ]
