# Generated by Django 3.2.13 on 2022-05-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20220526_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
