# Generated by Django 3.2.13 on 2022-05-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
