# Generated by Django 3.2.13 on 2022-05-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20220526_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('spring', 'Весна'), ('summer', 'Лето'), ('fall', 'Осень'), ('winter', 'Зима'), ('dresses', 'Платья'), ('skirts', 'Юбки')], default='summer', max_length=10, verbose_name='Коллекция'),
        ),
    ]
