# Generated by Django 3.2.13 on 2022-05-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20220526_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвета товара'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
    ]
