# Generated by Django 3.2.13 on 2022-05-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20220526_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(default='Обратный звонок', max_length=255, verbose_name='Тип обращения'),
        ),
    ]
