# Generated by Django 3.2.13 on 2022-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=10, verbose_name='Статус'),
        ),
    ]
