# Generated by Django 3.2.13 on 2022-05-30 06:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20220527_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение и цвет товара', 'verbose_name_plural': 'Изображение и цвет товара'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
