# Generated by Django 3.2.13 on 2022-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_alter_footerlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
    ]
