# Generated by Django 3.2.13 on 2022-05-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_alter_footerlink_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
