# Generated by Django 3.2.13 on 2022-05-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_auto_20220531_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name': 'Наши преимущества', 'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, null=True, to='mysite.Product')),
            ],
        ),
    ]
