# Generated by Django 3.2.13 on 2022-05-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_auto_20220531_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(blank=True, to='mysite.Product'),
        ),
    ]
