# Generated by Django 3.2.13 on 2022-05-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_alter_favorite_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(blank=True, to='mysite.Product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, default='Обратный звонок', max_length=255, verbose_name='Тип обращения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderuserinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
