# Generated by Django 3.2.13 on 2022-05-31 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0037_auto_20220531_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='products',
        ),
        migrations.AddField(
            model_name='favorite',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.product', verbose_name='Товары'),
        ),
    ]
