# Generated by Django 3.2.13 on 2022-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_auto_20220601_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Избранное',
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
