# Generated by Django 3.2.13 on 2022-06-09 04:39

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mysite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_orderproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Старая цена')),
                ('amount', models.PositiveIntegerField(default=1, validators=[mysite.validators.validate_amount], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.product', verbose_name='Товар')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.productimage', verbose_name='Id фото и продукт к которому привязан')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_lines', models.PositiveIntegerField(verbose_name='Количество линеек')),
                ('amount_products', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка')),
                ('final_price', models.PositiveIntegerField(verbose_name='Итого к оплате')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.orderuserinfo', verbose_name='Информация пользователя')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Старая цена')),
                ('amount', models.PositiveIntegerField(default=1, validators=[mysite.validators.validate_amount], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.product', verbose_name='Товар')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.productimage', verbose_name='Id фото и продукт к которому привязан')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image3',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
        migrations.AddField(
            model_name='aboutusimage',
            name='aboutus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.aboutus', verbose_name='Изображения'),
        ),
    ]
