# Generated by Django 3.2.13 on 2022-06-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0043_auto_20220609_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image',
        ),
        migrations.CreateModel(
            name='MainPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('mainpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.mainpage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Изображение для главной страницы',
                'verbose_name_plural': 'Изображения для главной страницы',
            },
        ),
    ]
