# Generated by Django 3.2.13 on 2022-06-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0044_auto_20220609_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(default='dsf', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MainPageImage',
        ),
    ]
