# Generated by Django 3.2.13 on 2022-06-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0045_auto_20220609_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='product_image_fk',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mysite.productimage', verbose_name='Id фото и продукт к которому привязан'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
