# Generated by Django 3.2.13 on 2022-06-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0049_auto_20220609_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='product_colour',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_colour',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
