# Generated by Django 3.2.13 on 2022-06-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0050_auto_20220610_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='product_image_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.productimage', verbose_name='Фото и цвет'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_image_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.productimage', verbose_name='Фото и цвет'),
        ),
    ]
