# Generated by Django 3.2.13 on 2022-06-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0051_auto_20220610_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
