# Generated by Django 3.2.13 on 2022-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0052_alter_cartproducts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_link',
        ),
    ]
