# Generated by Django 3.2.13 on 2022-06-21 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220620_1134'),
        ('mysite', '0058_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.myuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('finished', 'Завершен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
