# Generated by Django 3.2.13 on 2022-06-20 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='asdf', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='asdf', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.PositiveIntegerField(default=1435146, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
